/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedTopicsIndexRouteImport } from './routes/_authenticated/topics/index'
import { Route as ApiAutumnSplatRouteImport } from './routes/api/autumn/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedTopicsTopicIdRouteImport } from './routes/_authenticated/topics/$topicId'
import { Route as AuthenticatedTeamsSettingsRouteImport } from './routes/_authenticated/teams/settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopicsIndexRoute =
  AuthenticatedTopicsIndexRouteImport.update({
    id: '/topics/',
    path: '/topics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTopicsTopicIdRoute =
  AuthenticatedTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsSettingsRoute =
  AuthenticatedTeamsSettingsRouteImport.update({
    id: '/teams/settings',
    path: '/teams/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/': typeof AuthenticatedIndexRoute
  '/teams/settings': typeof AuthenticatedTeamsSettingsRoute
  '/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/topics': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/': typeof AuthenticatedIndexRoute
  '/teams/settings': typeof AuthenticatedTeamsSettingsRoute
  '/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/topics': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/teams/settings': typeof AuthenticatedTeamsSettingsRoute
  '/_authenticated/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/_authenticated/topics/': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/invitations'
    | '/'
    | '/teams/settings'
    | '/topics/$topicId'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/topics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/invitations'
    | '/'
    | '/teams/settings'
    | '/topics/$topicId'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/topics'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/invitations'
    | '/_authenticated/'
    | '/_authenticated/teams/settings'
    | '/_authenticated/topics/$topicId'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/_authenticated/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topics/': {
      id: '/_authenticated/topics/'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/topics/$topicId': {
      id: '/_authenticated/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicsTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/settings': {
      id: '/_authenticated/teams/settings'
      path: '/teams/settings'
      fullPath: '/teams/settings'
      preLoaderRoute: typeof AuthenticatedTeamsSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTeamsSettingsRoute: typeof AuthenticatedTeamsSettingsRoute
  AuthenticatedTopicsTopicIdRoute: typeof AuthenticatedTopicsTopicIdRoute
  AuthenticatedTopicsIndexRoute: typeof AuthenticatedTopicsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTeamsSettingsRoute: AuthenticatedTeamsSettingsRoute,
  AuthenticatedTopicsTopicIdRoute: AuthenticatedTopicsTopicIdRoute,
  AuthenticatedTopicsIndexRoute: AuthenticatedTopicsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
